name: "Build documentation index"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build index.html
    runs-on: ubuntu-latest

    steps:
    - name: Cache git metadata
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: .git
        key: git-metadata-${{ github.sha }}
        restore-keys: |
          git-metadata-${{ github.sha }}
          git-metadata

    - name: Checkout Github Pages branch
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        token: ${{ secrets.COMMAND_BOT_PAT }}

    - name: Get stable branches
      id: branch
      run: |
        branches=$(git ls-remote --heads origin "heads/stable[0-9][0-9]" | awk '{gsub(/^refs\/heads\/stable/, "", $2); print $2}' | sort -n -r | tr '\n' ' ')
        echo "branches=$branches" >> $GITHUB_OUTPUT

    - name: Setup php
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0

    - name: Generate index.html
      run: |
        php build/build-index.php ${{ steps.branch.outputs.branches }}
        mv build/index.html /tmp/index.html
        mv build/static/ /tmp/static/

    - name: Verify index.html structure and links
      run: |
        # Temporarily put index.html in build folder for verification
        cp /tmp/index.html build/index.html
        php build/verify-index.php

    - name: Switch to gh-pages branch
      if: github.event_name == 'push'
      run: |
        git fetch origin gh-pages
        git checkout gh-pages
        git config --local user.email "nextcloud-command@users.noreply.github.com"
        git config --local user.name "nextcloud-command"
    
    - name: Create Pull Request for documentation index deployment
      if: github.event_name == 'push'
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      id: cpr
      with:
        token: ${{ secrets.COMMAND_BOT_PAT }}
        commit-message: 'chore: deploy documentation index for ${{ github.ref_name }}'
        committer: nextcloud-command <nextcloud-command@users.noreply.github.com>
        author: nextcloud-command <nextcloud-command@users.noreply.github.com>
        signoff: true
        branch: 'automated/deploy/documentation-index-${{ github.ref_name }}'
        base: gh-pages
        title: 'Deploy documentation index for ${{ needs.stage.outputs.branch_name }}'
        body: 'Automated documentation index deployment from branch ${{ github.ref_name }}'
        delete-branch: true
        labels: 'automated, 3. to review'
  
    - name: Enable Pull Request Automerge
      if: github.event_name == 'push'
      run: gh pr merge --merge --auto "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.COMMAND_BOT_PAT }}
